# Generated by Django 4.0.1 on 2022-01-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='poem_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='poem',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poem',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poet',
            name='url',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='poem',
            name='poem_text',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=600)),
                ('date', models.DateTimeField(verbose_name='Date published')),
                ('connect_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.poem')),
            ],
        ),
    ]
