# Generated by Django 4.0.1 on 2022-01-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_poet_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poet',
            name='age',
        ),
        migrations.AlterField(
            model_name='poem',
            name='poem_text',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
