# Generated by Django 4.0.1 on 2022-01-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_poet_age_alter_poem_poem_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
