# Generated by Django 4.0.1 on 2022-02-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_poem_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='old',
            field=models.BooleanField(default=True),
        ),
    ]
