# Generated by Django 4.0.1 on 2022-11-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_poem_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='century',
            field=models.CharField(default='', max_length=100),
        ),
    ]
